server {
    listen 80;
    server_name lurnexa.com www.lurnexa.com;

    location = /favicon.ico { access_log off; log_not_found off; }
    
    location /static/ {
        alias /home/ubuntu/lurnexa_hrms/staticfiles/;
    }

    location /media/ {
        alias /home/ubuntu/lurnexa_hrms/media/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;
    }
}
