server {
    listen 443 ssl;
    server_name www.hr.lurnexatechnologies.in;
    ssl_certificate /etc/letsencrypt/live/hr.lurnexatechnologies.in/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/hr.lurnexatechnologies.in/privkey.pem; # managed by Certbot
    return 301 https://hr.lurnexatechnologies.in$request_uri;
}

server {
    if ($host = hr.lurnexatechnologies.in) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
    listen 80;
    server_name hr.lurnexatechnologies.in;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name hr.lurnexatechnologies.in;
    ssl_certificate /etc/letsencrypt/live/hr.lurnexatechnologies.in/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/hr.lurnexatechnologies.in/privkey.pem; # managed by Certbot

    client_max_body_size 100M;

    location = /favicon.ico { access_log off; log_not_found off; }

    location /static/ {
        alias /home/ubuntu/hr/staticfiles/;
    }

    location /media/ {
        alias /home/ubuntu/hr/media/;
    }

    location / {
        include proxy_params;
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    if ($host = www.hr.lurnexatechnologies.in) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
    listen 80;
    server_name www.hr.lurnexatechnologies.in;
    return 404; # managed by Certbot
}
